### PR TITLE
cmd/gomobile: xcframework and catalyst support

### PR DESCRIPTION
**Pull request by imWildCat**
Talked with @waylybaye offline, I decided to continue #63 and #45.

@waylybaye:

> I changed the build process and it will create 3 frameworks for ios, simulator and catalyst. Every framework has a fat library contains both arm64 and x86_64 (except ios that only needs arm64).
> 
> Finally create one xcframework from all 3 fat frameworks and this xcframework contains every platform and architecture.

Review comments at https://go-review.googlesource.com/c/mobile/+/288752 should be mostly resolved.

### CODE REVIEW

**Comment by imWildCat** [comment]
@googlebot I consent.

**Comment by waylybaye** [comment]
@googlebot I consent

**Comment by imWildCat** [comment]
@dpwiese could you please add your consent too? Thanks!

**Comment by dpwiese** [comment]
@googlebot I consent

**Pull request closed without merging**
